/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Elementos.*;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lopez
 */
public class Ventana extends javax.swing.JFrame {

    private Taller taller;
    JFileChooser fc;
    File file;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEncender = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnAcelerar = new javax.swing.JButton();
        btnFrenar = new javax.swing.JButton();
        txtVelocidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAbrirArchivo = new javax.swing.JButton();
        lTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLlantas = new javax.swing.JTextField();
        txtMotor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEncender.setText("Encender");
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnAcelerar.setText("Acelerar");
        btnAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcelerarActionPerformed(evt);
            }
        });

        btnFrenar.setText("Frenar");
        btnFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenarActionPerformed(evt);
            }
        });

        jLabel1.setText("Magnitud");

        btnAbrirArchivo.setText("Seleccionar archivo de texto");
        btnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivoActionPerformed(evt);
            }
        });

        lTxt.setText(" ");

        jLabel2.setText("Llantas:");

        jLabel3.setText("Motor:");

        txtLlantas.setEditable(false);

        txtMotor.setEditable(false);

        jLabel4.setText("Velocidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAbrirArchivo)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEncender)
                            .addComponent(btnAcelerar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFrenar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnApagar)
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEncender)
                            .addComponent(btnApagar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lTxt)))
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcelerar)
                    .addComponent(btnFrenar)
                    .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnAbrirArchivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
       if(taller.getVehiculo() == null){
           JOptionPane.showMessageDialog(this, new VehiculoNoExisteException().getMessage());
       }else{
           try{
            taller.getVehiculo().encender();
            lTxt.setText(taller.getVehiculo().getVelocidad()+"");
            JOptionPane.showMessageDialog(this, "Vehiculo encendido");
        }catch(VehiculoEncendidoException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       }
        
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
       if(taller.getVehiculo() == null){
           JOptionPane.showMessageDialog(this, new VehiculoNoExisteException().getMessage());
       }else{
           try{
                taller.getVehiculo().apagar();
                lTxt.setText("");
                JOptionPane.showMessageDialog(this, "Vehiculo apagado");
            }catch(VehiculoApagadoException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }catch (VehiculoAccidentadoException e1){
                JOptionPane.showMessageDialog(this, e1.getMessage());
                lTxt.setText("");
            }
       }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcelerarActionPerformed
        if(taller.getVehiculo() == null){
           JOptionPane.showMessageDialog(this, new VehiculoNoExisteException().getMessage());
        }else{
            try{
                int velocidadAceleracion = velocidadAceleracion = Integer.parseInt(txtVelocidad.getText());
                taller.getVehiculo().acelerar(velocidadAceleracion);
                lTxt.setText(taller.getVehiculo().getVelocidad()+"");
                JOptionPane.showMessageDialog(this, "Vehiculo acelerado a: "+ taller.getVehiculo().getVelocidad());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Ingrese el formato correcto.");
            }catch(VehiculoApagadoException e1){
                JOptionPane.showMessageDialog(this, "El vehiculo se encuentra apagado, por lo tanto no se puede acelerar.");
            }catch(VehiculoAccidentadoException e2){
                JOptionPane.showMessageDialog(this, e2.getMessage());
            }
            txtVelocidad.setText("");
        }
    }//GEN-LAST:event_btnAcelerarActionPerformed

    private void btnFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenarActionPerformed
        if(taller.getVehiculo() == null){
           JOptionPane.showMessageDialog(this, new VehiculoNoExisteException().getMessage());
        }else{
           try{
                int velocidadFrenado = Integer.parseInt(txtVelocidad.getText());
                taller.getVehiculo().frenar(velocidadFrenado);
                lTxt.setText(taller.getVehiculo().getVelocidad()+"");
                JOptionPane.showMessageDialog(this, "Vehiculo frenado a: "+ taller.getVehiculo().getVelocidad());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Ingrese el formato correcto.");
            }catch(VehiculoApagadoException e1){
                JOptionPane.showMessageDialog(this, "El vehiculo se encuentra apagado, por lo tanto no se puede frenar.");
            }catch(VehiculoDetenidoException e2){
                JOptionPane.showMessageDialog(this, e2.getMessage());
            }catch(VehiculoPatinandoException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
                lTxt.setText(taller.getVehiculo().getVelocidad()+"");
            }
            txtVelocidad.setText("");
        }
    }//GEN-LAST:event_btnFrenarActionPerformed

    private void btnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivoActionPerformed
        fc = new JFileChooser();
        
        FileNameExtensionFilter fne = new FileNameExtensionFilter(".txt", "txt");
        
        fc.setFileFilter(fne);
        fc.showOpenDialog(this);
        file = fc.getSelectedFile();
        
        try {
            taller.getLectorArchivoTexto().leerArchivo(file);
            JOptionPane.showMessageDialog(this, "Archivo abierto");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "El arhivo seleccionado no se puede abrir.");
        } catch (NullPointerException e){
        }catch (FormatoNoValidoException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        try{
            crearVehiculo();
            llenarTxtFieldMotorLlanta();
        }catch (FormatoNoValidoException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnAbrirArchivoActionPerformed
    
    public void llenarTxtFieldMotorLlanta(){
        if(taller.getVehiculo().getLlanta() instanceof LlantaBuena){
            txtLlantas.setText("Buenas");
        }else if(taller.getVehiculo().getLlanta() instanceof LlantaBonita){
            txtLlantas.setText("Bonitas");
        }else if(taller.getVehiculo().getLlanta() instanceof LlantaBarata){
            txtLlantas.setText("Baratas");
        }
        if(taller.getVehiculo().getMotor() instanceof Motor1000){
            txtMotor.setText("1000 cc");
        }else if(taller.getVehiculo().getMotor() instanceof Motor2000){
            txtMotor.setText("2000 cc");
        }else if(taller.getVehiculo().getMotor() instanceof Motor3000){
            txtMotor.setText("3000 cc");
        }
    }
    
    public void crearVehiculo() throws FormatoNoValidoException{
        try{
            this.taller.setVehiculo();
        }catch (FormatoNoValidoException e){
            throw e;
        }
    }
    
    public void setTaller(Taller taller){
        this.taller = taller;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArchivo;
    private javax.swing.JButton btnAcelerar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEncender;
    private javax.swing.JButton btnFrenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lTxt;
    private javax.swing.JTextField txtLlantas;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
